version: '3.7'

services:
  developer-mongo:
    container_name: ${APP_NAME}-mongodb
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT-27017}:27017
    expose:
      - 27017
    environment:
      - MONGODB_DATABASE=${MONGO_DATABASE}
      - MONGODB_USER=${MONGO_USER}
      - MONGODB_PASS=${MONGO_PASS}
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=docker
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_DATA-DIR=/data/db
    volumes:
      - /data/db